import {build} from 'esbuild';
import {readFile,writeFile,mkdir,copyFile,rm} from 'node:fs/promises';
await rm('dist/runtime',{recursive:true,force:true});
await mkdir('dist/runtime',{recursive:true});
await build({entryPoints:['src/separation-worker.js'],outfile:'dist/separation-worker.js',bundle:true,format:'esm',platform:'browser',target:'es2022',minify:true,legalComments:'eof'});
const root='node_modules/onnxruntime-web/dist/';
for(const file of ['ort-wasm-simd-threaded.wasm','ort-wasm-simd-threaded.mjs'])await copyFile(root+file,'dist/runtime/'+file);
const licenses=await Promise.all(['node_modules/web-audio-separation/LICENSE','licenses/onnxruntime-LICENSE.txt'].map(p=>readFile(p,'utf8')));
await writeFile('dist/THIRD_PARTY_NOTICES.txt','SingKeys uses web-audio-separation 0.3.1 (PffftSTFT) and ONNX Runtime Web 1.30.0.\nKim Vocal 2 model: '+ 'https://huggingface.co/Politrees/UVR_resources (MIT, downloaded at runtime; pinned SHA-256 in source).\n\n'+licenses.join('\n\n'));
console.log('Built browser separation worker and local inference runtime.');
